### ISSUE TITLE
Required fields are sometimes not marked as such

### ISSUE THREAD

**Issue by rotty3000** [yaacov/crdtoapi#1]
I have a CRD with:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  ...
spec:
  ...
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
             ...
          required:
            - apiVersion
            - kind
            - metadata
            - spec
```
After running:
```shell
npx crdtoapi -i ./crds/ -o ./openapi.yaml
npx crdtotypes -i ./openapi.yaml -o ./src/crd/
```
I get a type having:
```typescript
  ...
  /** metadata
   *
   * @required {false}
   * @originalType {FooMetadata}
   */
  metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
  /** spec
   *
   * @required {false}
   */
  spec?: FooSpec
```

PR forthcoming.
