### ISSUE TITLE
additionalProperties keyword is not supported

### ISSUE THREAD

**Issue by rotty3000** [yaacov/crdtoapi#4]
CRDs may use the `additionalProperties` property to indicate that the property is a map (a.k.a. Dictionary, HashMap, Associative Array).

e.g.:
```yaml
    settings:
      additionalProperties:
        type: string
      description: Provider settings.
      type: object
```
This means, the property `settings` is a _map_ whose values are of type `string`.

Ref: [Dictionaries, HashMaps and Associative Arrays](https://swagger.io/docs/specification/data-models/dictionaries/)

In TypeScript this should result in:
```typescript
settings: {[key: string]: string}
```

PR forthcoming.
